vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       images_event:
           uri_prefix: /assets/images/database/event
           upload_destination: '%kernel.project_dir%/public/assets/images/database/event'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
